name: bottle_spinner
description: A simple bottle spinner game in Flutter.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add any other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/floor.jpg
    - images/logo.jpg
    - images/bottle.png
